Plot CRUD commands for admins
AusTrakka/austrakka2-cli pull request #216
Opened 2023-04-18 06:47 UTC by claresloggett

Add commands to manage plots within projects.

To be useable need to deploy server PR https://github.com/AusTrakka/austrakka-portal/pull/901

2023-04-21 01:38 UTC, samcarswell requested changes

2023-04-21 01:38 UTC, samcarswell commented on austrakka/utils/helpers/project.py
> +    response = api_get(
You can now do this in one line with `return api_get(path=f"{PROJECT_PATH}/abbrev/{abbrev}")['data']`

`api_get` throws an `UnknownResponseException` if data is not included so there's no need to check or conditionally return the entire response as all endpoints now return the standard response

2023-04-21 01:38 UTC, samcarswell commented on austrakka/components/plot/funcs.py
> +def _get_plot_by_abbrev(abbrev: str):
Can we move this to `utils/helpers` to be consistent

2023-05-02 03:59 UTC, samcarswell commented
Don't merge this until AB#4121 has been merged to dev and the options here fixed

2023-05-10 07:25 UTC, claresloggett commented
@samcarswell I think you've already resolved the outstanding comments you had yourself - was there anything else?

2023-05-12 03:31 UTC, samcarswell approved these changes

2023-05-12 03:58 UTC, merged