AB#4477 - Changed log messages to show only essentials at success level or higher.
AusTrakka/austrakka2-cli pull request #291
Opened 2023-07-24 01:30 UTC by viatunimelb

AB#4477

2023-07-25 11:01 UTC, claresloggett requested changes
The aim here is to use a log level of SUCCESS in our routine logs, right?

The bulk of the messages I see are the "Matched" and "Done" messages, which you've switched to INFO, so those are probably the most important changes for verbosity? Looks good.

For some of the other changes, I personally think you were right the first time, I like the original log levels! I've left a few comments on these. Sorry to be finicky.

2023-07-26 01:33 UTC, viatunimelb commented on austrakka/components/sequence/sync/sync_workflow.py
>          ctx[DF].at[ctx[IDX], STATUS_KEY] = MISSING
It signifies both. For the purpose of self healing, the distinction isn't important.

2023-07-26 01:38 UTC, viatunimelb commented on austrakka/components/sequence/sync/sync_workflow.py
Hot swapping is a destructive process, unlike purge which currently just soft-deletes by moving files to trash. The event is worthy of a warning and should appear in logs for traceability.

2023-07-26 01:41 UTC, viatunimelb commented on austrakka/components/sequence/sync/sync_workflow.py
> +
It's important when the process is killed and then resumes from the beginning of the current action. Logging the start event makes that log trail less confusing.

2023-07-28 04:42 UTC, claresloggett approved these changes

2023-07-28 05:43 UTC, merged