AB#6216 - Added command to purge sample metadata.
AusTrakka/austrakka2-cli pull request #521
Opened 2024-09-17 04:47 UTC by viatunimelb

[AB#6216](https://dev.azure.com/mduphl/66de697f-df03-4f5d-b5b4-0df4487db257/_workitems/edit/6216)

Companion PRs:
https://github.com/AusTrakka/austrakka-portal/pull/1785
https://github.com/AusTrakka/austrakka2-infra/pull/116

2024-09-18 05:44 UTC, samcarswell approved these changes

2024-09-20 02:52 UTC, claresloggett requested changes

2024-09-20 02:52 UTC, claresloggett commented on austrakka/components/sample/__init__.py
> +def sample_purge(sample_id: str):
This command should be hidden behind the AT_CMD_SET env variable

2024-09-26 05:43 UTC, claresloggett approved these changes

2024-09-26 05:53 UTC, merged