6183 user perm v2
AusTrakka/austrakka2-cli pull request #526
Opened 2024-10-02 00:22 UTC by mannSheth

Initial Pr for the user cli commands

2024-10-17 02:37 UTC, claresloggett requested changes
Looks fine; nothing removed will be needed once new roles are assigned.

I'd just suggest adding `org.add_command(privilege_subcommands('User'))`

2024-10-17 02:38 UTC, claresloggett commented
Adding blocked label so that we don't deploy until we assign scopes to appropriate people via new roles

2024-10-17 03:25 UTC, mannSheth commented
This should be complete as the only thing that needs to be maintained by the old endpoints is the user get command which the cli does not make use of anyway

2024-12-17 04:34 UTC, claresloggett commented
Needs to be updated to match the altered Me endpoint

2026-05-12 04:39 UTC, closed without merging

2026-05-12 04:39 UTC, samcarswell commented
Closing this, as we have merged v1 and v2 user controllers